package com.soubu.CRMProject.base.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Client".
 */
@Entity(nameInDb = "Client")
public class Client {

    @Id(autoincrement = true)
    private Long id;
    private long client_id;
    private String name;
    private Integer type;
    private String phone;
    private String email;
    private String fax;
    private String network;
    private String area;
    private String summary;
    private String zip_code;
    private String follow_state;
    private String from;
    private String industry;
    private Integer scale;
    private String principal;
    private String address;
    private String main_products;
    private String turnover;
    private String empirical_mode;
    private String major_business;

    @Generated
    public Client() {
    }

    public Client(Long id) {
        this.id = id;
    }

    @Generated
    public Client(Long id, long client_id, String name, Integer type, String phone, String email, String fax, String network, String area, String summary, String zip_code, String follow_state, String from, String industry, Integer scale, String principal, String address, String main_products, String turnover, String empirical_mode, String major_business) {
        this.id = id;
        this.client_id = client_id;
        this.name = name;
        this.type = type;
        this.phone = phone;
        this.email = email;
        this.fax = fax;
        this.network = network;
        this.area = area;
        this.summary = summary;
        this.zip_code = zip_code;
        this.follow_state = follow_state;
        this.from = from;
        this.industry = industry;
        this.scale = scale;
        this.principal = principal;
        this.address = address;
        this.main_products = main_products;
        this.turnover = turnover;
        this.empirical_mode = empirical_mode;
        this.major_business = major_business;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getClient_id() {
        return client_id;
    }

    public void setClient_id(long client_id) {
        this.client_id = client_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getNetwork() {
        return network;
    }

    public void setNetwork(String network) {
        this.network = network;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getZip_code() {
        return zip_code;
    }

    public void setZip_code(String zip_code) {
        this.zip_code = zip_code;
    }

    public String getFollow_state() {
        return follow_state;
    }

    public void setFollow_state(String follow_state) {
        this.follow_state = follow_state;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public Integer getScale() {
        return scale;
    }

    public void setScale(Integer scale) {
        this.scale = scale;
    }

    public String getPrincipal() {
        return principal;
    }

    public void setPrincipal(String principal) {
        this.principal = principal;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getMain_products() {
        return main_products;
    }

    public void setMain_products(String main_products) {
        this.main_products = main_products;
    }

    public String getTurnover() {
        return turnover;
    }

    public void setTurnover(String turnover) {
        this.turnover = turnover;
    }

    public String getEmpirical_mode() {
        return empirical_mode;
    }

    public void setEmpirical_mode(String empirical_mode) {
        this.empirical_mode = empirical_mode;
    }

    public String getMajor_business() {
        return major_business;
    }

    public void setMajor_business(String major_business) {
        this.major_business = major_business;
    }

}
