package com.soubu.CRMProject.base.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Product".
 */
@Entity(nameInDb = "Product")
public class Product {

    @Id(autoincrement = true)
    private Long id;
    private long product_id;
    private Long classification;
    private String title;
    private Double price;
    private String img;
    private Long stock;
    private Long cost;
    private Integer buy_state;
    private Long width;
    private String product_name;
    private String ingredient;
    private String use;
    private Integer season;
    private Integer crafts;
    private String color;
    private String flower;

    @Generated
    public Product() {
    }

    public Product(Long id) {
        this.id = id;
    }

    @Generated
    public Product(Long id, long product_id, Long classification, String title, Double price, String img, Long stock, Long cost, Integer buy_state, Long width, String product_name, String ingredient, String use, Integer season, Integer crafts, String color, String flower) {
        this.id = id;
        this.product_id = product_id;
        this.classification = classification;
        this.title = title;
        this.price = price;
        this.img = img;
        this.stock = stock;
        this.cost = cost;
        this.buy_state = buy_state;
        this.width = width;
        this.product_name = product_name;
        this.ingredient = ingredient;
        this.use = use;
        this.season = season;
        this.crafts = crafts;
        this.color = color;
        this.flower = flower;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(long product_id) {
        this.product_id = product_id;
    }

    public Long getClassification() {
        return classification;
    }

    public void setClassification(Long classification) {
        this.classification = classification;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public Long getStock() {
        return stock;
    }

    public void setStock(Long stock) {
        this.stock = stock;
    }

    public Long getCost() {
        return cost;
    }

    public void setCost(Long cost) {
        this.cost = cost;
    }

    public Integer getBuy_state() {
        return buy_state;
    }

    public void setBuy_state(Integer buy_state) {
        this.buy_state = buy_state;
    }

    public Long getWidth() {
        return width;
    }

    public void setWidth(Long width) {
        this.width = width;
    }

    public String getProduct_name() {
        return product_name;
    }

    public void setProduct_name(String product_name) {
        this.product_name = product_name;
    }

    public String getIngredient() {
        return ingredient;
    }

    public void setIngredient(String ingredient) {
        this.ingredient = ingredient;
    }

    public String getUse() {
        return use;
    }

    public void setUse(String use) {
        this.use = use;
    }

    public Integer getSeason() {
        return season;
    }

    public void setSeason(Integer season) {
        this.season = season;
    }

    public Integer getCrafts() {
        return crafts;
    }

    public void setCrafts(Integer crafts) {
        this.crafts = crafts;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getFlower() {
        return flower;
    }

    public void setFlower(String flower) {
        this.flower = flower;
    }

}
