package com.soubu.CRMProject.base.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "User".
 */
@Entity(nameInDb = "User")
public class User {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private String phone;

    @NotNull
    private String user_id;
    private java.util.Date password;

    @Generated
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    @Generated
    public User(Long id, String name, String phone, String user_id, java.util.Date password) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.user_id = user_id;
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @NotNull
    public String getUser_id() {
        return user_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser_id(@NotNull String user_id) {
        this.user_id = user_id;
    }

    public java.util.Date getPassword() {
        return password;
    }

    public void setPassword(java.util.Date password) {
        this.password = password;
    }

}
